In [1]:
import numpy as np

# 1. Creating an Array:

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) 
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

# 2.Some Inbuilt Function:

In [6]:
np.zeros((3,4)) #Create an array with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=np.int16) #Create an array with 1 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
np.arange(10,35,5) #Create an array of evenly spaced values (step value) 

array([10, 15, 20, 25, 30])

In [9]:
np.linspace(0,2,9) #Create an array of evenlyspaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.random.random((2,2))

array([[0.06989122, 0.95612798],
       [0.16617225, 0.48023489]])

In [11]:
np.empty((3,2)) #It gives some garbage value

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# 3.Inspecting Array:

In [12]:
a = np.array([1,2,3]) #Array dimensions
a.shape


(3,)

In [13]:
a = np.array([[1,2,3],[4,5,8]])
a.shape

(2, 3)

In [14]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.shape

(2, 2, 3)

In [15]:
a = np.array([1,2,3])  #Length of array
len(a)

3

In [16]:
a = np.array([[1,2,3],[4,5,6]])
len(a)

2

In [17]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
len(a)

2

In [18]:
a = np.array([1,2,3])
a.ndim

1

In [19]:
a = np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [20]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.ndim

3

In [21]:
a = np.array([1,2,3]) #Number of array elements
a.size

3

In [22]:
a = np.array([[1,2,3],[4,5,6]])
a.size

6

In [23]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.size

12

In [24]:
a = np.array([1,2,3]) #Data type of array elements
a.dtype

dtype('int64')

In [25]:
a = np.array([[1,2,3],[4,5,6]])
a.dtype

dtype('int64')

In [26]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.dtype

dtype('int64')

In [27]:
a = np.array([1,2,3])  #Name of data type
a.dtype.name

'int64'

In [28]:
a = np.array([[1,2,3],[4,5,6]])
a.dtype.name

'int64'

In [29]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.dtype.name

'int64'

In [30]:
a = np.array([1,2,3])   #Convert an array to a different type
a.astype(float)

array([1., 2., 3.])

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.astype(float)

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

# 4.Data Types:

In [33]:
import numpy as np   #Signed 64-bit integer typres
a = np.array(([1,2,3]), dtype=np.int64)
a
a.dtype

dtype('int64')

In [34]:
a = np.array([10,20,30],dtype=np.float32)
(a,a.dtype)

(array([10., 20., 30.], dtype=float32), dtype('float32'))

# 5.Array Mathematics:

In [35]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1.5, 2.0, 3.0],
              [1.0, 1.25, 1.5]])

In [36]:
g = a-b   #Subtraction M1
g

array([[-0.5 ,  0.  ,  0.  ],
       [ 3.  ,  3.75,  4.5 ]])

In [37]:
np.subtract(a, b)  #Subtraction M2

array([[-0.5 ,  0.  ,  0.  ],
       [ 3.  ,  3.75,  4.5 ]])

In [38]:
g = a+b    #Addition M1
g

array([[2.5 , 4.  , 6.  ],
       [5.  , 6.25, 7.5 ]])

In [39]:
np.add(b,a)   #Addition M2

array([[2.5 , 4.  , 6.  ],
       [5.  , 6.25, 7.5 ]])

In [40]:
g = a/b   #Division M1
g

array([[0.66666667, 1.        , 1.        ],
       [4.        , 4.        , 4.        ]])

In [41]:
np.divide(a,b)   #Division M3

array([[0.66666667, 1.        , 1.        ],
       [4.        , 4.        , 4.        ]])

In [42]:
g = a*b  #Multiplication M1
g

array([[1.5 , 4.  , 9.  ],
       [4.  , 6.25, 9.  ]])

In [43]:
np.multiply(a,b)   #Multiplication M2

array([[1.5 , 4.  , 9.  ],
       [4.  , 6.25, 9.  ]])

In [44]:
np.exp(b)    #Exponentiation

array([[ 4.48168907,  7.3890561 , 20.08553692],
       [ 2.71828183,  3.49034296,  4.48168907]])

In [45]:
np.sqrt(b)   #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [1.        , 1.11803399, 1.22474487]])

In [46]:
np.sin(a)  #Sine of each element in a

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [47]:
np.cos(b)  #Cosine of each element in b

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [ 0.54030231,  0.31532236,  0.0707372 ]])

In [48]:
np.log(a)  #Natural logarithm (ln) of each element in a

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [49]:
c = np.array([[1,2],  #Matrix Multiplication 
              [3,4]])
d = np.array([[1,1],
              [1,1]])
c.dot(d)

array([[3, 3],
       [7, 7]])

### 6.Comparison


In [50]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 0, 3],
              [4, 7, 6]])

In [51]:
a == b   #Element-wise comparison

array([[ True, False,  True],
       [ True, False,  True]])

In [52]:
a<2     #Element-wise condition

array([[ True, False, False],
       [False, False, False]])

In [53]:
a = np.array([[1, 2, 3],    #Array-wise comparison
              [4, 5, 6]])

b = np.array([[1, 2, 3],
              [4, 5, 6]])


np.array_equal(a,b)

True

# 7.Aggregate Functions:

In [54]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 0, 3],
              [4, 7, 6]])

In [55]:
a.sum()   #Array-wise sum

21

In [56]:
a.min()  #Array-wise minimum value

1

In [57]:
b.max(axis=0)   #Maximum value of an array row

array([4, 7, 6])

In [58]:
a.max()

6

In [59]:
b.cumsum(axis=1)  #Cumulative sum

array([[ 1,  1,  4],
       [ 4, 11, 17]])

In [60]:
a = np.array([[1,2,3],   #Mean
            [4,5,6]])
a.mean()

3.5

In [61]:
a = np.array([7,4,9,5,3,0,1,6,2,8]) #Median
np.median(a)

4.5

In [62]:
x = np.array([1, 2, 3])  #Correlational coefficient
y = np.array([2, 4, 6])

np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

In [63]:
a = np.array([[3, 7, 2],  #Standard Deviation
              [9, 1, 5]])
np.std(a)

2.8136571693556887

# 8.Aggregate Functions:

In [64]:
a = np.array([1,2,3,4,5,6])  #Creates a new array object that shares the same data as a
h = a.view()
h

array([1, 2, 3, 4, 5, 6])

In [65]:
a = np.array([1,2,3,4,5,6])  #Creates a deep copy of a
b = np.copy(a)
b

array([1, 2, 3, 4, 5, 6])

In [66]:
a = np.array([1,2,3,4,5,6])   #Same as np.copy(a)
b = a.copy()
b

array([1, 2, 3, 4, 5, 6])

# 9.Sorting Arrays:


In [67]:
a = np.array([3,1,4,2])   #Sort an array
a.sort()
a

array([1, 2, 3, 4])

In [68]:
a = np.array([[3, 7, 1],    #Sort the elements of an array's axis
              [2, 9, 5],
              [4, 8, 6]]) 
#FOR 2D ARRAY:
a.sort(axis=0)    #axis=0: sort column-wise
print("Column-wise:",a)
a.sort(axis=1)    #axis=1: sort row-wise
print("Row-wise",a)

Column-wise: [[2 7 1]
 [3 8 5]
 [4 9 6]]
Row-wise [[1 2 7]
 [3 5 8]
 [4 6 9]]


# 10.Subsetting,Slicing,Indexing:

### (i).Subsetting:

In [69]:
import numpy as np      #Select the element at the 2nd index
a = np.array([7,2,9])
a[2]                     #For 1D  


9

In [70]:
b = np.array([[3,6,5],    #Select the element at row1 column2
              [7,4,9]])
b[1,2]                    #For 2D

9

In [71]:
c = np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])
c[1,1,1]                    #For 3D - c[page, row, column]

11

### (ii).Slicing:

In [72]:
a = np.array([1,2,3,6,7,5,9])  #Select items at index 0 and 1
a[1:5]

array([2, 3, 6, 7])

In [73]:
b = np.array([[5,6,8],     #For 2-D
              [1,3,9]])
print(b[0:2,1])            #b[range, column1]
print(b[0,0:2])            #b[row0 , range]

[6 3]
[5 6]


In [74]:
c = np.array([[[1,2,3],       #For 3-D
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])
print(c[1, :, :])       # c[page range,row range,column range]
print(c[:, :, 0])       # column 0 from all pages
print(c[1, :, 1:])      # page 1, all rows, cols 1→end

[[ 7  8  9]
 [10 11 12]]
[[ 1  4]
 [ 7 10]]
[[ 8  9]
 [11 12]]


In [75]:
a = np.array([1,3,5])    # Reversed array (For 1-D)
a[::-1]                  # a[start:end:step]

array([5, 3, 1])

In [76]:
a = np.array([[1,2,3],            #For 2-D
              [4,5,6]])
print(a[::-1])              #Flips vertically
print(a[:,::-1])            #Flips horizontally
print(a[::-1 , ::-1])  #Reverse both rows and columns

[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[6 5 4]
 [3 2 1]]


### (iii).Boolean Indexing

In [77]:
#Select elements from (a) less than 5

a = np.array([1,2,3,4,5,6])         #For 1-D
a[a<5]

array([1, 2, 3, 4])

In [78]:
a = np.array([[1,2,3],             #For 2-D
              [4,5,6]])
a[a<4]

array([1, 2, 3])

In [79]:
c = np.array([[[1,11,3],           #For 3-D
               [4,5,6]],
              [[7,8,9],
               [10,15,12]]])
c[c<10]

array([1, 3, 4, 5, 6, 7, 8, 9])

### (iv).Fancy Indexing

In [80]:
#For 1-D
a = np.array([10, 20, 30, 40, 50])
print(a[[0, 2, 4]])       # Get elements at positions 0, 2, 4

[10 30 50]


In [81]:
#For 2-D
b = np.array([[10, 20, 30],    
              [40, 50, 60]])
print(b[[0,1],:])     #Pick specific rows , #rows 0 and 1
print(b[:,[0,1]])     #Pick specific columns , #all rows,only columns 0 & 1

[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]]


In [82]:
#For 3-D 
import numpy as np
c = np.array([[[0,1,2,3],    
               [4,5,6,7],
               [8,9,10,11]],
             [[12,13,14,15],  
              [16,17,18,19],
              [20,21,22,23]]])
#Fancy Indexing on Pages
print(c[[0,1]])              #Pick both pages
print(c[[1]])                #Pick only page 1

#Fancy Indexing on Rows
print(c[:,[0,2]])            #Pick row 0 and row2 from each page

#Fancy Indexing on Columns
print(c[:,:,[1,3]])          #Pick col 1 and col3 from each row of page

#Fancy Indexing with Multiple Axes Together
print(c[[0,1],[1,2],[2,3]])  #Pick specific elements

#This works element-wise:
#>>>From page 0, row 1, col 2 → 6
#>>>From page 1, row 2, col 3 → 23

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]
[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]]
[ 6 23]


# 11.Array Manipulation:

### (i).Transposing Array:

In [83]:
a = np.array([[1,2,3],       #Swap rows and columns
              [4,5,6]])
print(a.T)                   #Method1:(Simple transpose)
print(np.transpose(a))        #Method2:(Flexible)

#For 2D arrays, np.transpose(a) and a.T are the same

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [84]:
a = np.array([[[1,2,3,4],
               [5,6,7,8]],
              [[9,10,11,12],
               [13,14,15,16]]])
print(np.transpose(a, (1,0,2)))  #Method2:(Flexible(you can specify axis order))

[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]


### (iii).Changing Array Shape:

In [85]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
a.ravel()                     #Flatten to 1D

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
a = np.array([[[1,2,3,4],
              [5,6,7,8]],
             [[9,10,11,12],
              [13,14,15,16]]])
a.reshape(8,2)              #Reshape to dimension given

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

### (iii).Adding/Removing Elements:

In [87]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
a.resize((2,10))        #Return a new array (if ele is not present it adds 0) 
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [88]:
import numpy as np
a = np.array([10,20,30])

print(np.append(a,[40,50]))      #Add at end
print(np.insert(a,1,[15]))       #Insert at index 1
print(np.delete(a,1))            #Delete element at index 1

#np.append(arr, values, axis=None)
#np.insert(arr, index, values, axis=None)
#np.delete(arr, index, axis=None)

[10 20 30 40 50]
[10 15 20 30]
[10 30]
